all:
	g++ ProjectData.cpp -c -o ./ProjectData.o
	g++ WindLoad.cpp -c -o ./WindLoad.o
	g++ SnowLoad.cpp -c -o ./SnowLoad.o
	g++ FlatRoofWindLoad.cpp -c -o ./FlatRoofWindLoad.o
	g++ ConsoleProject1.cpp ProjectData.o WindLoad.o SnowLoad.o FlatRoofWindLoad.o -o ./ConsoleProject1
